/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-09-10 06:57:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  \r\n");
      out.write(" <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Deep Judge - 在线跳水评分系统</title>\r\n");
      out.write("    \r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"css/pages/reports.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"js/echarts.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar navbar-fixed-top\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a class=\"brand\" href=\"index.html\">\r\n");
      out.write("\t\t\t\tDeep Judge - 在线跳水评分系统\t\t\t\r\n");
      out.write("\t\t\t</a>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"nav-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav pull-right\">\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tAccount\r\n");
      out.write("\t\t\t\t\t\t\t<b class=\"caret\"></b>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">Settings</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">Help</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-user\"></i> \r\n");
      out.write("\t\t\t\t\t\t\tHinton\r\n");
      out.write("\t\t\t\t\t\t\t<b class=\"caret\"></b>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form class=\"navbar-search pull-right\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"search-query\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div><!--/.nav-collapse -->\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div> <!-- /container -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div> <!-- /navbar-inner -->\r\n");
      out.write("\t\r\n");
      out.write("</div> <!-- /navbar -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"subnavbar\">\r\n");
      out.write("  <div class=\"subnavbar-inner\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <ul class=\"mainnav\">\r\n");
      out.write("        <li><a href=\"index.jsp\"><i class=\"icon-dashboard\"></i><span>评分</span> </a> </li>\r\n");
      out.write("        <li class=\"active\"><a href=\"reports.html\"><i class=\"icon-list-alt\"></i><span>报告</span> </a> </li>\r\n");
      out.write("        <!--<li><a href=\"guidely.html\"><i class=\"icon-facetime-video\"></i><span>回放</span> </a></li>-->\r\n");
      out.write("        <!--<li><a href=\"charts.html\"><i class=\"icon-bar-chart\"></i><span>Charts</span> </a> </li> -->\r\n");
      out.write("        <!--<li><a href=\"shortcodes.html\"><i class=\"icon-code\"></i><span>Shortcodes</span> </a> </li> -->\r\n");
      out.write("        <li class=\"dropdown\"><a href=\"javascript:;\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> <i class=\"icon-long-arrow-down\"></i><span>更多</span> <b class=\"caret\"></b></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a href=\"icons.html\">Icons</a></li>\r\n");
      out.write("            <li><a href=\"faq.html\">FAQ</a></li>\r\n");
      out.write("            <li><a href=\"pricing.html\">Pricing Plans</a></li>\r\n");
      out.write("            <li><a href=\"login.html\">Login</a></li>\r\n");
      out.write("            <li><a href=\"signup.html\">Signup</a></li>\r\n");
      out.write("            <li><a href=\"error.html\">404</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /container --> \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /subnavbar-inner --> \r\n");
      out.write("</div>\r\n");
      out.write("<!-- /subnavbar -->\r\n");
      out.write("    \r\n");
      out.write("<div class=\"container\" style=\"position:fixed;z-index:3;margin-left:500px;margin-top:100px;display:none;\" id=\"caloriWindow\">\r\n");
      out.write("<div class=\"dragclass\" id=\"main\" style=\"LEFT: 100px; TOP: 100px\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"span6\">\r\n");
      out.write("          <div class=\"widget\">\r\n");
      out.write("            <div class=\"widget-header\" style=\"background-color:black\"> <i class=\"icon-file\"></i>\r\n");
      out.write("              <h3>卡路里窗口</h3>\r\n");
      out.write("\t\t\t  <button id=\"CloseWindow\" type=\"button\" class=\"btn btn-default\">×</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /widget-header -->\r\n");
      out.write("            <div class=\"widget-content\" id=\"ChatWindow\">\r\n");
      out.write("\t\t\t\t<div style=\"text-align:center;\" id=\"ChatScroll\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/ss.jpg\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"text-align:center\">\r\n");
      out.write("\t\t\t\t\t<h3>食物种类：蛋炒饭</h3>\r\n");
      out.write("\t\t\t\t\t<h3>卡路里：516大卡</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            <!-- /widget-content --> \r\n");
      out.write("          </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"main-inner\">\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>最常选择动作及得分</h3>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /widget-header -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main1\" style=\"width: 480px;height:250px;margin:0 auto\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /widget-content -->\r\n");
      out.write("\t\t\t\t\t</div> <!-- /widget -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>身体健康状况</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\">更新身高</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\">更新体重</button>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /widget-header -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main2\" style=\"width: 480px;height:250px;margin:0 auto\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /widget-content -->\r\n");
      out.write("\t\t\t\t\t</div> <!-- /widget -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-list-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>每日得分情况</h3>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /widget-header -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main3\" style=\"width: 480px;height:250px;margin:0 auto\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /widget-content -->\r\n");
      out.write("\t\t\t\t\t</div> <!-- /widget -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-header\" >\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-list-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>每日食物摄入卡路里</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<form  action=\"load\" class=\"btn btn-default\" method=\"post\" enctype=\"multipart/form-data\" target=\"nm_iframe\" /> \r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"button\" value=\"选择食物图片\" onclick=\"filePhoto.click()\" class=\"btn btn-default\"/>\r\n");
      out.write("  \t\t\t  \t\t\t\t <input type=\"file\" id=\"filePhoto\" name=\"filePhoto\" onchange=\"doChange(this);\" contentEditable=\"false\" accept=\"text/html\" style=\"visibility: hidden; position: absolute;\"/>\r\n");
      out.write("       \t\t  \t\t\t\t <!-- <input type=\"file\" class=\"btn btn-default\" name=\"file1\" id=\"file1\">  -->\r\n");
      out.write("       \t\t                <input type=\"submit\" class=\"btn btn-default\" name=\"Submit\" value=\"上传图片\" > \r\n");
      out.write("       \t\t                <input type=\"button\" class=\"btn btn-default\" id=\"OpenWindow\" onclick=\"myFunction()\" value=\"开始计算\">\r\n");
      out.write("\t\t\t                </form>\r\n");
      out.write("\t\t\t                <iframe id=\"id_iframe\" name=\"nm_iframe\" style=\"display:none;\"></iframe> \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-default\" id=\"OpenWindow\">上传食物照片</button>\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"form-control\" style=\"margin-top:8px;width:100px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>早餐</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>午餐</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>晚餐</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /widget-header -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main4\" style=\"width: 480px;height:250px;margin:0 auto\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /widget-content -->\r\n");
      out.write("\t\t\t\t\t</div> <!-- /widget -->\r\n");
      out.write("\t\t\t\t</div> <!-- /span6 -->\r\n");
      out.write("\t      \t\r\n");
      out.write("\t\t\t</div> <!-- /row -->\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div> <!-- /main-inner -->\r\n");
      out.write("</div> <!-- /main -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <div class=\"footer-inner\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"span12\"> &copy; 2017 <a href=\"#\">Hinton团队</a> 版权所有</a></div>\r\n");
      out.write("        <!-- /span12 --> \r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /row --> \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /container --> \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /footer-inner --> \r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script src=\"js/excanvas.min.js\"></script>\r\n");
      out.write("<script src=\"js/chart.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"js/base.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t$(\"#CloseWindow\").click(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#caloriWindow\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#OpenWindow\").click(function() {\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tfunction show(){\r\n");
      out.write("\t\t\t\t$(\"#caloriWindow\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tsetTimeout(show,2000);// 注意函数名没有引号和括弧！\r\n");
      out.write("\t\t\t// 使用setInterval(\"show()\",3000);会报“缺少对象”\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t//$(\"#caloriWindow\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var myChart1 = echarts.init(document.getElementById('main1'));\r\n");
      out.write("var myChart2 = echarts.init(document.getElementById('main2'));\r\n");
      out.write("var myChart3 = echarts.init(document.getElementById('main3'));\r\n");
      out.write("var myChart4 = echarts.init(document.getElementById('main4'));\r\n");
      out.write("option1 = {\r\n");
      out.write("    title: {\r\n");
      out.write("        text: ''\r\n");
      out.write("    },\r\n");
      out.write("    tooltip: {},\r\n");
      out.write("    legend: {\r\n");
      out.write("        data: ['', '']\r\n");
      out.write("    },\r\n");
      out.write("    radar: {\r\n");
      out.write("        // shape: 'circle',\r\n");
      out.write("        name: {\r\n");
      out.write("            textStyle: {\r\n");
      out.write("                color: '#fff',\r\n");
      out.write("                backgroundColor: '#999',\r\n");
      out.write("                borderRadius: 3,\r\n");
      out.write("                padding: [3, 5]\r\n");
      out.write("           }\r\n");
      out.write("        },\r\n");
      out.write("        indicator: [\r\n");
      out.write("           { name: '207B', max: 10},\r\n");
      out.write("           { name: '405B', max: 10},\r\n");
      out.write("           { name: '207C', max: 10},\r\n");
      out.write("           { name: '307C', max: 10},\r\n");
      out.write("           { name: '5253B', max: 10},\r\n");
      out.write("           { name: '109C', max: 10}\r\n");
      out.write("        ]\r\n");
      out.write("    },\r\n");
      out.write("    series: [{\r\n");
      out.write("        name: '预算 vs 开销（Budget vs spending）',\r\n");
      out.write("        type: 'radar',\r\n");
      out.write("        // areaStyle: {normal: {}},\r\n");
      out.write("        data : [\r\n");
      out.write("            {\r\n");
      out.write("                value : [8.5, 8.0, 8.0, 9.0, 9.5, 9.0],\r\n");
      out.write("                name : '最近一次得分'\r\n");
      out.write("            }, \r\n");
      out.write("\t\t\t{\r\n");
      out.write("                value : [8.0, 8.5, 9.0, 8.0, 8.0, 9.0],\r\n");
      out.write("                name : '平均得分'\r\n");
      out.write("            }\r\n");
      out.write("        ]\r\n");
      out.write("    }]\r\n");
      out.write("};\r\n");
      out.write("myChart1.setOption(option1, true);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("option2 = {\r\n");
      out.write("    title : {\r\n");
      out.write("        text: '',\r\n");
      out.write("        subtext: ''\r\n");
      out.write("    },\r\n");
      out.write("    tooltip : {\r\n");
      out.write("        trigger: 'axis'\r\n");
      out.write("    },\r\n");
      out.write("    legend: {\r\n");
      out.write("        data:['身高','体重']\r\n");
      out.write("    },\r\n");
      out.write("    toolbox: {\r\n");
      out.write("        show : true,\r\n");
      out.write("        feature : {\r\n");
      out.write("            dataView : {show: false, readOnly: false},\r\n");
      out.write("            magicType : {show: true, type: ['line', 'bar']},\r\n");
      out.write("            restore : {show: true},\r\n");
      out.write("            saveAsImage : {show: true}\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("    calculable : true,\r\n");
      out.write("    xAxis : [\r\n");
      out.write("        {\r\n");
      out.write("            type : 'category',\r\n");
      out.write("            data : ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']\r\n");
      out.write("        }\r\n");
      out.write("    ],\r\n");
      out.write("    yAxis : [\r\n");
      out.write("        {\r\n");
      out.write("            type : 'value'\r\n");
      out.write("        }\r\n");
      out.write("    ],\r\n");
      out.write("    series : [\r\n");
      out.write("        {\r\n");
      out.write("            name:'身高',\r\n");
      out.write("            type:'bar',\r\n");
      out.write("            data:[180.1, 180.2, 180.2, 180.2, 180.2, 180.2, 180.2, 180.2, 180.2, 180.2, 180.2, 180.2]\r\n");
      out.write("            \r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            name:'体重',\r\n");
      out.write("            type:'bar',\r\n");
      out.write("            data:[65.1, 62, 64, 67, 65, 64, 65, 67, 66, 65.1, 64, 65.1]\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("    ]\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("myChart2.setOption(option2, true);\r\n");
      out.write("\r\n");
      out.write("var dataAll = [\r\n");
      out.write("    [\r\n");
      out.write("        [1, 8.04],\r\n");
      out.write("        [1, 6.0],\r\n");
      out.write("        [2, 8.04],\r\n");
      out.write("        [3, 8.04],\r\n");
      out.write("        [4, 8.04],\r\n");
      out.write("        [5, 8.04],\r\n");
      out.write("        [6.0, 8.04],\r\n");
      out.write("        [8.0, 6.95],\r\n");
      out.write("        [9.0, 8.81],\r\n");
      out.write("        [6.0, 7.24],\r\n");
      out.write("        [4.0, 4.26],\r\n");
      out.write("        [7.0, 4.82],\r\n");
      out.write("        [5.0, 5.68]\r\n");
      out.write("    ]\r\n");
      out.write("];\r\n");
      out.write("\r\n");
      out.write("var markLineOpt = {\r\n");
      out.write("    animation: false,\r\n");
      out.write("    label: {\r\n");
      out.write("        normal: {\r\n");
      out.write("            formatter: '',\r\n");
      out.write("            textStyle: {\r\n");
      out.write("                align: 'right'\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("    lineStyle: {\r\n");
      out.write("        normal: {\r\n");
      out.write("            type: 'solid'\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("    tooltip: {\r\n");
      out.write("        formatter: ''\r\n");
      out.write("    }\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("option3 = {\r\n");
      out.write("    title: {\r\n");
      out.write("        text: '',\r\n");
      out.write("        x: 'center',\r\n");
      out.write("        y: 0\r\n");
      out.write("    },\r\n");
      out.write("    grid: [\r\n");
      out.write("        {x: '5%', y: '20%', width: '90%', height: '60%'},\r\n");
      out.write("    ],\r\n");
      out.write("    tooltip: {\r\n");
      out.write("        formatter: 'Group {a}: ({c})'\r\n");
      out.write("    },\r\n");
      out.write("    xAxis : [\r\n");
      out.write("        {\r\n");
      out.write("            type : 'category',\r\n");
      out.write("            data : ['1号','2号','3号','4号','5号','6号','7号','8号','9号','10号','11号','12号']\r\n");
      out.write("        }\r\n");
      out.write("    ],\r\n");
      out.write("    yAxis: [\r\n");
      out.write("        {gridIndex: 0, min: 0, max: 10}\r\n");
      out.write("    ],\r\n");
      out.write("    series: [\r\n");
      out.write("        {\r\n");
      out.write("            name: 'I',\r\n");
      out.write("            type: 'scatter',\r\n");
      out.write("            xAxisIndex: 0,\r\n");
      out.write("            yAxisIndex: 0,\r\n");
      out.write("            data: dataAll[0],\r\n");
      out.write("            markLine: markLineOpt\r\n");
      out.write("        }\r\n");
      out.write("    ]\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("myChart3.setOption(option3, true);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("option4 = {\r\n");
      out.write("    title : {\r\n");
      out.write("        text: '',\r\n");
      out.write("        subtext: ''\r\n");
      out.write("    },\r\n");
      out.write("    tooltip : {\r\n");
      out.write("        trigger: 'axis'\r\n");
      out.write("    },\r\n");
      out.write("    legend: {\r\n");
      out.write("        data:['早餐','午餐','晚餐']\r\n");
      out.write("    },\r\n");
      out.write("    toolbox: {\r\n");
      out.write("        show : true,\r\n");
      out.write("        feature : {\r\n");
      out.write("            dataView : {show: false, readOnly: false},\r\n");
      out.write("            magicType : {show: true, type: ['line', 'bar']},\r\n");
      out.write("            restore : {show: true},\r\n");
      out.write("            saveAsImage : {show: true}\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("    calculable : true,\r\n");
      out.write("    xAxis : [\r\n");
      out.write("        {\r\n");
      out.write("            type : 'category',\r\n");
      out.write("            data : ['1号','2号','3号','4号','5号','6号','7号','8号','9号','10号','11号','12号']\r\n");
      out.write("        }\r\n");
      out.write("    ],\r\n");
      out.write("    yAxis : [\r\n");
      out.write("        {\r\n");
      out.write("            type : 'value'\r\n");
      out.write("        }\r\n");
      out.write("    ],\r\n");
      out.write("    series : [\r\n");
      out.write("        {\r\n");
      out.write("            name:'早餐',\r\n");
      out.write("            type:'bar',\r\n");
      out.write("            data:[100, 80, 110, 100, 80, 70, 80, 50, 60, 80, 70, 80]\r\n");
      out.write("            \r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            name:'午餐',\r\n");
      out.write("            type:'bar',\r\n");
      out.write("            data:[65.1, 64, 62, 66, 67, 65, 64, 63, 65, 66, 67, 64]\r\n");
      out.write("            \r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            name:'晚餐',\r\n");
      out.write("            type:'bar',\r\n");
      out.write("            data:[25, 30, 32, 34, 35, 37, 36, 35, 34, 30, 32]\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("    ]\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("myChart4.setOption(option4, true);\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
